"""
Wave-0 cross-SDK byte-exactness parity tests.

These assert the Python SDK produces output BYTE-IDENTICAL to the TypeScript
SDK 4.8.0 for the protocol hashing/EIP-712 hot path. The golden vectors in
``tests/fixtures/cross_sdk/wave0_hashing.json`` are generated by the REAL TS
functions (``sdk-js/scripts/gen-wave0-vectors.cjs``):

- ``canonicalJsonStringify`` / ``computeResultHash``  (canonical JSON + keccak)
- ``ProofGenerator.hashContent``                      (keccak256(utf8))
- AIP-2 ``QuoteBuilder`` EIP-712 sign + ``computeHash``

A failure here means a Python agent and a TS agent would compute different
hashes/signatures for the same logical action — i.e. they could not interoperate
on-chain. Do not "fix" by regenerating without re-running the TS generator.
"""

import json
from pathlib import Path

import pytest
from eth_account import Account

from agirails.builders.delivery_proof import compute_output_hash
from agirails.builders.quote import QuoteBuilder, QuoteMessage
from agirails.protocol.proofs import ProofGenerator
from agirails.types.message import compute_result_hash
from agirails.utils.canonical_json import canonical_json_dumps

FIXTURE = Path(__file__).parent.parent / "fixtures" / "cross_sdk" / "wave0_hashing.json"


@pytest.fixture(scope="module")
def golden() -> dict:
    with open(FIXTURE) as f:
        return json.load(f)


# id -> Python input. MUST mirror VEC in gen-wave0-vectors.cjs exactly.
CANONICAL_INPUTS = {
    "empty_obj": {},
    "simple": {"a": "x", "b": "y"},
    "key_sort": {"b": 2, "a": 1},
    "int": {"n": 1},
    "float_int_valued": {"amount": 1.0},
    "float_60": {"estimatedTime": 60.0},
    "neg_zero": {"x": -0.0},
    "float_decimal": {"rate": 0.1},
    "float_decimal2": {"marketRate": 0.0345},
    "float_neg": {"v": -1.5},
    "large_e21": {"big": 1e21},
    "large_e20": {"big": 1e20},
    "large_e16": {"big": 1e16},
    "small_e7": {"small": 1e-7},
    "small_e6": {"small": 1e-6},
    "small_e8_mant": {"small": 1.5e-8},
    "nested": {"nested": {"z": 1, "a": 2.0}},
    "array_floats": {"arr": [1.0, 2.5, -0.0, 3]},
    "bool_null": {"t": True, "f": False, "n": None},
    "unicode": {"emoji": "\U0001F389", "txt": "héllo"},
    "control_chars": {"s": 'line1\nline2\ttab"quote\\back'},
    "u2028": {"s": "a b c"},
    "del_char": {"s": "ab"},
    "string_top": "hello",
    "number_top": 42,
    "float_top": 1.0,
    "bool_top": True,
    "null_top": None,
    "deeply_nested": {"a": {"b": {"c": {"d": [1, 2, {"e": 5.0}]}}}},
    "justification": {
        "reason": "gpu",
        "estimatedTime": 120,
        "computeCost": 0.5,
        "breakdown": {"gpu": 0.4, "overhead": 0.1},
    },
}


class TestCanonicalJsonByteExactness:
    @pytest.mark.parametrize("vid", list(CANONICAL_INPUTS.keys()))
    def test_canonical_string_matches_ts(self, vid: str, golden: dict) -> None:
        expected = golden["canonical"][vid]["canonical"]
        assert canonical_json_dumps(CANONICAL_INPUTS[vid]) == expected, (
            f"[{vid}] canonical JSON diverged from TS"
        )

    @pytest.mark.parametrize("vid", list(CANONICAL_INPUTS.keys()))
    def test_result_hash_matches_ts(self, vid: str, golden: dict) -> None:
        expected = golden["canonical"][vid]["resultHash"]
        assert compute_result_hash(CANONICAL_INPUTS[vid]) == expected, (
            f"[{vid}] computeResultHash diverged from TS"
        )

    def test_integer_valued_float_drops_fraction(self, golden: dict) -> None:
        # The canonical bug this wave fixes: 1.0 -> "1", -0.0 -> "0".
        assert canonical_json_dumps({"amount": 1.0}) == '{"amount":1}'
        assert canonical_json_dumps({"x": -0.0}) == '{"x":0}'
        assert canonical_json_dumps({"big": 1e16}) == '{"big":10000000000000000}'
        assert canonical_json_dumps({"small": 1e-7}) == '{"small":1e-7}'


class TestProofGeneratorKeccak:
    def test_hash_content_matches_ts_keccak(self, golden: dict) -> None:
        # hash_content().content_hash mirrors TS ProofGenerator.hashContent:
        # raw keccak256(utf8(content)), NOT canonical-JSON hashing.
        gen = ProofGenerator()  # default is now keccak256
        for entry in golden["hashContent"].values():
            assert gen.hash_content(entry["input"]).content_hash == entry["hash"], (
                f"ProofGenerator.hash_content diverged for {entry['input']!r:.40}"
            )

    def test_default_algorithm_is_keccak(self) -> None:
        assert ProofGenerator()._algorithm == "keccak256"


class TestComputeOutputHash:
    def test_string_deliverable_is_json_quoted(self, golden: dict) -> None:
        # compute_output_hash("hello") must equal computeResultHash("hello")
        # (TS JSON-quotes a string before hashing).
        expected = golden["canonical"]["string_top"]["resultHash"]
        assert compute_output_hash("hello") == expected
        assert compute_output_hash("hello") == compute_result_hash("hello")

    def test_object_deliverable_matches(self, golden: dict) -> None:
        inp = CANONICAL_INPUTS["justification"]
        assert compute_output_hash(inp) == golden["canonical"]["justification"]["resultHash"]


class TestAIP2QuoteSigning:
    def _quote(self, golden: dict) -> QuoteMessage:
        return QuoteMessage.from_dict(golden["quote"]["quote"])

    def test_justification_hash_matches(self, golden: dict) -> None:
        qb = QuoteBuilder()
        assert (
            qb.compute_justification_hash(golden["quote"]["justification"])
            == golden["quote"]["justificationHash"]
        )

    def test_compute_hash_matches_ts(self, golden: dict) -> None:
        qb = QuoteBuilder()
        assert qb.compute_hash(self._quote(golden)) == golden["quote"]["computeHash"]

    def test_eip712_signature_matches_ts(self, golden: dict) -> None:
        acct = Account.from_key(golden["quote"]["privateKey"])
        qb = QuoteBuilder(account=acct)
        quote = self._quote(golden)
        sig = qb.sign_quote(quote, golden["quote"]["kernelAddress"])
        assert sig == golden["quote"]["signature"], "EIP-712 quote signature diverged from TS"

    def test_verify_recovers_provider(self, golden: dict) -> None:
        # Isolate signature recovery (the cross-SDK crypto), not the wall-clock
        # business rules: the golden quote uses fixed past timestamps.
        acct = Account.from_key(golden["quote"]["privateKey"])
        qb = QuoteBuilder(account=acct)
        quote = self._quote(golden)
        quote.signature = qb.sign_quote(quote, golden["quote"]["kernelAddress"])
        recovered = qb._recover_quote_signer(quote, golden["quote"]["kernelAddress"])
        assert recovered.lower() == golden["quote"]["signerAddress"].lower()

    def test_signer_address_matches(self, golden: dict) -> None:
        acct = Account.from_key(golden["quote"]["privateKey"])
        assert acct.address.lower() == golden["quote"]["signerAddress"].lower()
